### ISSUE TITLE
The Version of LILIGO's Lora32 SX1276

### ISSUE THREAD

**Issue by winnie2007** [FLN1021/SX1276_Receive_LBJ#2]
I tried to run the program on LoRa32 V2.1_1.6 Disaster-Radio. 
And can it run on another version : Paxcounter ?
They both include a 868MHz function on SX1276
What version did you use? 
Thanks for reply  : )
This is BH2XHY , a Chinese Ham and CR fan 👍

**Comment by FLN1021** [comment]
As far as I know these two version only have difference on software, there are no difference on hardware so this program should work on both. I used the Paxcounter version, but there should be no difference using the other one.

**Comment by winnie2007** [comment]
> As far as I know these two version only have difference on software, there are no difference on hardware so this program should work on both. I used the Paxcounter version, but there should be no difference using the other one.

OK thanks a lot. I'll try the other version. By the way, are you a fun of China Railway? Can we add contact details?
I‘m a Chinese high school student, and my QQ number is 3506220641. If it's convenient for you, I'll be honerd to be friends with you
