### ISSUE TITLE
需要中文版MD

### ISSUE THREAD

**Issue by sliverwolf233** [FLN1021/SX1276_Receive_LBJ#3]
我想我已经翻译完成了,可能并不是您的原意,但是我尽力了 lol

**Comment by sliverwolf233** [comment]
emm gh有点不会用QaQ

**Comment by FLN1021** [comment]
关于这个由于众所周知的原因已经github上类似的项目都没有提供中文版项目介绍，所以我对公开提供中文版项目介绍持保守态度，希望您能理解。如果您真的需要的话可以考虑留下您的联系方式，谢谢。
